import os

USE_FINE_TUNED_INDEX = False
GOOGLE_TRANSLATE_GLOSSARY_ID = "demo1-search-glossary"
PROJECT_ID = os.getenv("PROJECT_ID")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
API_KEY = os.getenv("API_KEY")
